"""
Tracing API for CreateAgentsAI.

This module exposes a minimal, decoupled interface for trace storage.
Users can integrate any observability platform by implementing `ITraceStore`.

Quick Start
-----------
Using built-in trace stores::

    from createagents import CreateAgent
    from createagents.tracing import FileTraceStore

    agent = CreateAgent(
        provider="openai",
        model="gpt-4o-mini",
        trace_store=FileTraceStore()
    )

Creating a custom trace store (minimal)::

    from createagents.tracing import ITraceStore

    class MyStore(ITraceStore):
        def save(self, data: dict) -> None:
            # data is a plain dict - send to your backend
            requests.post("https://my-backend/traces", json=data)

OpenTelemetry Integration::

    from createagents.tracing import ITraceStore
    from opentelemetry import trace

    class OTelStore(ITraceStore):
        def __init__(self):
            self.tracer = trace.get_tracer(__name__)

        def save(self, data: dict) -> None:
            with self.tracer.start_span(data["operation"]) as span:
                span.set_attribute("trace_id", data["trace_id"])
                span.set_attribute("run_type", data["run_type"])
                if data.get("error_message"):
                    span.set_status(StatusCode.ERROR, data["error_message"])

Data Format
-----------
The `save(data)` method receives a dict with these keys:

Core (always present):
    - trace_id: str - Unique identifier for the trace
    - run_id: str - Unique identifier for this span/run
    - run_type: str - 'chat', 'llm', 'tool', 'chain', 'agent'
    - operation: str - Human-readable operation name
    - event: str - 'trace.start', 'trace.end', 'tool.call', etc.
    - timestamp: str - ISO format timestamp

Context:
    - parent_run_id: str | None - Parent span ID
    - session_id: str | None - Session grouping ID
    - agent_name: str | None - Name of the agent
    - model: str | None - Model being used
    - status: str | None - 'success' or 'error'

Payloads:
    - inputs: dict | None - Input data
    - outputs: dict | None - Output data
    - duration_ms: float | None - Duration in milliseconds

Error Tracking (OpenTelemetry/Datadog):
    - error_message: str | None - Error description
    - error_type: str | None - Exception class name
    - error_stack: str | None - Stack trace

Token/Cost Tracking (LangSmith):
    - input_tokens: int | None - Input token count
    - output_tokens: int | None - Output token count
    - total_tokens: int | None - Total tokens used
    - cost_usd: float | None - Estimated cost in USD

Events
------
Core events emitted by the framework:
    - trace.start: Beginning of a trace
    - trace.end: End of a trace
    - llm.request: LLM API request
    - llm.response: LLM API response
    - tool.call: Tool execution start
    - tool.result: Tool execution result
    - tool.log: Log entry from user code inside a tool

tool.log Event Format (auto-generated by ContextAwareLogger):
    {
        'event': 'tool.log',
        'trace_id': str,
        'run_id': str,
        'parent_run_id': str | None,
        'level': 'DEBUG' | 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL',
        'message': str,
        'logger_name': str,
        'timestamp': str (ISO format),
        'operation': str,
        'run_type': str,
    }

Exports
-------
Interface:
    ITraceStore: Abstract interface - implement `save(data: dict)` method.

Built-in Stores:
    FileTraceStore: Persists traces to JSONL files.
    InMemoryTraceStore: Keeps traces in memory (dev/testing).

Context Access (advanced):
    get_current_trace_context: Get the current trace context from within a tool.
"""

from .._private.domain.interfaces.tracing import ITraceStore
from .._private.domain.value_objects.tracing.context_var import (
    get_current_trace_context,
)
from .._private.infra import FileTraceStore, InMemoryTraceStore

__all__ = [
    # Interface (contract for custom implementations)
    'ITraceStore',
    # Built-in Stores
    'FileTraceStore',
    'InMemoryTraceStore',
    # Context Access (advanced)
    'get_current_trace_context',
]
